In [3]:
import numpy as np


In [4]:
arr1 = np.array({1,2,3,4,5})
arr1

array({1, 2, 3, 4, 5}, dtype=object)

In [7]:
arr2 = np.array(any[[1,2,3],[4,5,6]])
arr2

TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
filled = np.full((2,2),7)
filled

array([[7, 7],
       [7, 7]])

In [ ]:
sequence = np.arrange(1,10,2)
sequence

AttributeError: module 'numpy' has no attribute 'arrange'

In [ ]:
random_arr = np.random.random((2,2,))
random_arr

array([[0.9083185 , 0.31014471],
       [0.06688913, 0.28982082]])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print (np.sum(a))
print (np.mean(a))
print (np.sqrt(a))

6
2.0
[1.         1.41421356 1.73205081]


In [ ]:
import numpy as np
arr = (1,2,3,4,5,6)
arr


(1, 2, 3, 4, 5, 6)

In [ ]:
arr_reshaped = arr.reshape((2,3))
arr_reshaped

AttributeError: 'tuple' object has no attribute 'reshape'

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

#specific
print (arr[1,:])

[4 5 6]


In [ ]:
import numpy as np
matrix = np.arrange(1,10).reshape(3,3)
total_sum = np.sum(matrix)
print ("Matrix:\n", matrix)
print ("Sum of all elements:", total_sum)

AttributeError: module 'numpy' has no attribute 'arrange'

In [ ]:
identity_matrix = np.eye(5)
print ("Identity matrix :\n" , identity_matrix)

Identity matrix :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
import numpy as np
data = np.random.rand(1000000)

mean = np.mean(data)
std_dev = np.std(data)

print ("Mean:", mean)
print ("Standard deviation:", std_dev)

Mean: 0.4999038568988138
Standard deviation: 0.2885443539871261
